// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: gigantic_messaging.proto

package gigantic_messaging

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BaseResponse_ResponseStatus int32

const (
	BaseResponse_SUCCESS_OK            BaseResponse_ResponseStatus = 0
	BaseResponse_ERROR_INTERNAL        BaseResponse_ResponseStatus = 1
	BaseResponse_ERROR_INVALID_REQUEST BaseResponse_ResponseStatus = 2
)

// Enum value maps for BaseResponse_ResponseStatus.
var (
	BaseResponse_ResponseStatus_name = map[int32]string{
		0: "SUCCESS_OK",
		1: "ERROR_INTERNAL",
		2: "ERROR_INVALID_REQUEST",
	}
	BaseResponse_ResponseStatus_value = map[string]int32{
		"SUCCESS_OK":            0,
		"ERROR_INTERNAL":        1,
		"ERROR_INVALID_REQUEST": 2,
	}
)

func (x BaseResponse_ResponseStatus) Enum() *BaseResponse_ResponseStatus {
	p := new(BaseResponse_ResponseStatus)
	*p = x
	return p
}

func (x BaseResponse_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseResponse_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gigantic_messaging_proto_enumTypes[0].Descriptor()
}

func (BaseResponse_ResponseStatus) Type() protoreflect.EnumType {
	return &file_gigantic_messaging_proto_enumTypes[0]
}

func (x BaseResponse_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseResponse_ResponseStatus.Descriptor instead.
func (BaseResponse_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_gigantic_messaging_proto_rawDescGZIP(), []int{1, 0}
}

type EmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email     string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	MessageId int32  `protobuf:"varint,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Body      string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gigantic_messaging_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gigantic_messaging_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_gigantic_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *EmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type BaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    BaseResponse_ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=gigantic_messaging.BaseResponse_ResponseStatus" json:"status,omitempty"`
	Message   string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageId int32                       `protobuf:"varint,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gigantic_messaging_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gigantic_messaging_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_gigantic_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResponse) GetStatus() BaseResponse_ResponseStatus {
	if x != nil {
		return x.Status
	}
	return BaseResponse_SUCCESS_OK
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResponse) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

var File_gigantic_messaging_proto protoreflect.FileDescriptor

var file_gigantic_messaging_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x69, 0x67, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67, 0x69, 0x67, 0x61,
	0x6e, 0x74, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x56,
	0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xe0, 0x01, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x67, 0x69, 0x67, 0x61, 0x6e, 0x74,
	0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x19,
	0x0a, 0x15, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x32, 0xc3, 0x01, 0x0a, 0x11, 0x47, 0x69,
	0x67, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12,
	0x51, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x2e, 0x67,
	0x69, 0x67, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x67, 0x69, 0x67, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x20, 0x2e, 0x67, 0x69, 0x67, 0x61, 0x6e, 0x74, 0x69, 0x63,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x69, 0x67, 0x61, 0x6e, 0x74,
	0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x3e, 0x0a, 0x1d, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x73, 0x65, 0x2e, 0x67, 0x69,
	0x67, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x42, 0x16, 0x47, 0x69, 0x67, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0xa2, 0x02, 0x02, 0x47, 0x4d, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gigantic_messaging_proto_rawDescOnce sync.Once
	file_gigantic_messaging_proto_rawDescData = file_gigantic_messaging_proto_rawDesc
)

func file_gigantic_messaging_proto_rawDescGZIP() []byte {
	file_gigantic_messaging_proto_rawDescOnce.Do(func() {
		file_gigantic_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(file_gigantic_messaging_proto_rawDescData)
	})
	return file_gigantic_messaging_proto_rawDescData
}

var file_gigantic_messaging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gigantic_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gigantic_messaging_proto_goTypes = []interface{}{
	(BaseResponse_ResponseStatus)(0), // 0: gigantic_messaging.BaseResponse.ResponseStatus
	(*EmailRequest)(nil),             // 1: gigantic_messaging.EmailRequest
	(*BaseResponse)(nil),             // 2: gigantic_messaging.BaseResponse
}
var file_gigantic_messaging_proto_depIdxs = []int32{
	0, // 0: gigantic_messaging.BaseResponse.status:type_name -> gigantic_messaging.BaseResponse.ResponseStatus
	1, // 1: gigantic_messaging.GiganticMessaging.SendEmail:input_type -> gigantic_messaging.EmailRequest
	1, // 2: gigantic_messaging.GiganticMessaging.SendEmailStream:input_type -> gigantic_messaging.EmailRequest
	2, // 3: gigantic_messaging.GiganticMessaging.SendEmail:output_type -> gigantic_messaging.BaseResponse
	2, // 4: gigantic_messaging.GiganticMessaging.SendEmailStream:output_type -> gigantic_messaging.BaseResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gigantic_messaging_proto_init() }
func file_gigantic_messaging_proto_init() {
	if File_gigantic_messaging_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gigantic_messaging_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gigantic_messaging_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gigantic_messaging_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gigantic_messaging_proto_goTypes,
		DependencyIndexes: file_gigantic_messaging_proto_depIdxs,
		EnumInfos:         file_gigantic_messaging_proto_enumTypes,
		MessageInfos:      file_gigantic_messaging_proto_msgTypes,
	}.Build()
	File_gigantic_messaging_proto = out.File
	file_gigantic_messaging_proto_rawDesc = nil
	file_gigantic_messaging_proto_goTypes = nil
	file_gigantic_messaging_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GiganticMessagingClient is the client API for GiganticMessaging service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GiganticMessagingClient interface {
	SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	SendEmailStream(ctx context.Context, opts ...grpc.CallOption) (GiganticMessaging_SendEmailStreamClient, error)
}

type giganticMessagingClient struct {
	cc grpc.ClientConnInterface
}

func NewGiganticMessagingClient(cc grpc.ClientConnInterface) GiganticMessagingClient {
	return &giganticMessagingClient{cc}
}

func (c *giganticMessagingClient) SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/gigantic_messaging.GiganticMessaging/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giganticMessagingClient) SendEmailStream(ctx context.Context, opts ...grpc.CallOption) (GiganticMessaging_SendEmailStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GiganticMessaging_serviceDesc.Streams[0], "/gigantic_messaging.GiganticMessaging/SendEmailStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &giganticMessagingSendEmailStreamClient{stream}
	return x, nil
}

type GiganticMessaging_SendEmailStreamClient interface {
	Send(*EmailRequest) error
	Recv() (*BaseResponse, error)
	grpc.ClientStream
}

type giganticMessagingSendEmailStreamClient struct {
	grpc.ClientStream
}

func (x *giganticMessagingSendEmailStreamClient) Send(m *EmailRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *giganticMessagingSendEmailStreamClient) Recv() (*BaseResponse, error) {
	m := new(BaseResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GiganticMessagingServer is the server API for GiganticMessaging service.
type GiganticMessagingServer interface {
	SendEmail(context.Context, *EmailRequest) (*BaseResponse, error)
	SendEmailStream(GiganticMessaging_SendEmailStreamServer) error
}

// UnimplementedGiganticMessagingServer can be embedded to have forward compatible implementations.
type UnimplementedGiganticMessagingServer struct {
}

func (*UnimplementedGiganticMessagingServer) SendEmail(context.Context, *EmailRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (*UnimplementedGiganticMessagingServer) SendEmailStream(GiganticMessaging_SendEmailStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendEmailStream not implemented")
}

func RegisterGiganticMessagingServer(s *grpc.Server, srv GiganticMessagingServer) {
	s.RegisterService(&_GiganticMessaging_serviceDesc, srv)
}

func _GiganticMessaging_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiganticMessagingServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gigantic_messaging.GiganticMessaging/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiganticMessagingServer).SendEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiganticMessaging_SendEmailStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GiganticMessagingServer).SendEmailStream(&giganticMessagingSendEmailStreamServer{stream})
}

type GiganticMessaging_SendEmailStreamServer interface {
	Send(*BaseResponse) error
	Recv() (*EmailRequest, error)
	grpc.ServerStream
}

type giganticMessagingSendEmailStreamServer struct {
	grpc.ServerStream
}

func (x *giganticMessagingSendEmailStreamServer) Send(m *BaseResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *giganticMessagingSendEmailStreamServer) Recv() (*EmailRequest, error) {
	m := new(EmailRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GiganticMessaging_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gigantic_messaging.GiganticMessaging",
	HandlerType: (*GiganticMessagingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _GiganticMessaging_SendEmail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendEmailStream",
			Handler:       _GiganticMessaging_SendEmailStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gigantic_messaging.proto",
}
